# Base image
FROM node:22.2.0-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy application code
COPY . ./

# Expose port
EXPOSE 5050

# Start development server
CMD ["npm", "run", "dev"]
