export const DummyData = [
  {
    _id: '23063240',
    name: 'Mai Thai Hoang',
    age: 30,
    job: 'Frontend Engineer',
    country: 'Centec',
    status: 'Active',
  },
  {
    _id: '23063272',
    name: 'Nguyen Van A',
    age: 60,
    job: 'Technical writer',
    country: 'The Mett',
    status: 'Deactivated',
  },
  {
    _id: '23044043',
    name: 'Tran Thi B',
    age: 20,
    job: 'Technical writer',
    country: '',
    status: 'Active',
  },
  {
    _id: '22063145',
    name: '',
    age: 40,
    job: 'Technical writer',
    country: '',
    status: 'Active',
  },
  {
    _id: '',
    name: '',
    age: 90,
    job: 'Technical writer',
    country: '',
    status: 'Active',
  },
  {
    _id: '23063272',
    name: 'Nguyen Van A',
    age: 60,
    job: 'Technical writer',
    country: 'The Mett',
    status: 'Deactivated',
  },
  {
    _id: '23044043',
    name: 'Tran Thi B',
    age: 20,
    job: 'Technical writer',
    country: '',
    status: 'Active',
  },
  {
    _id: '23063272',
    name: 'Nguyen Van A',
    age: 60,
    job: 'Technical writer',
    country: 'The Mett',
    status: 'Deactivated',
  },
  {
    _id: '23044043',
    name: 'Tran Thi B',
    age: 20,
    job: 'Technical writer',
    country: '',
    status: 'Active',
  },
];
