# HTTP: ACME 인증 경로만 처리하고 나머지는 HTTPS로 리다이렉트

server {
    listen 80;
    server_name seonshine.net www.seonshine.net;

    location ~ /.well-known/acme-challenge/ {
        allow all;
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
