# Base image
FROM node:22.2.0-alpine

# Set working directory
WORKDIR /app

# Install Yarn
RUN apk add --no-cache yarn

# Set Yarn network timeout and registry
RUN yarn config set network-timeout 600000
RUN yarn config set registry "https://registry.npmjs.org"

# Copy package files
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy application code
COPY . .

# Expose port
EXPOSE 3000

# Start development server
CMD ["yarn", "dev"]