name: Build and Deploy

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "seonshine_frontend/**"
      - "seonshine_backend/**"
      - "seonshine_db/**"
      - "seonshine_fileserver/**"

jobs:
  check-changed-files:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.check.outputs.frontend }}
      backend: ${{ steps.check.outputs.backend }}
      fileserver: ${{ steps.check.outputs.fileserver }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Check for changed files
        id: check
        run: |
          FRONTEND_CHANGED=$(git diff --name-only HEAD HEAD~1 | grep 'seonshine_frontend' || echo '')
          BACKEND_CHANGED=$(git diff --name-only HEAD HEAD~1 | grep 'seonshine_backend' || echo '')
          FILESERVER_CHANGED=$(git diff --name-only HEAD HEAD~1 | grep 'seonshine_fileserver' || echo '')

          if [ "$FRONTEND_CHANGED" != '' ]; then
            echo "::set-output name=frontend::true"
          fi
          if [ "$BACKEND_CHANGED" != '' ]; then
            echo "::set-output name=backend::true"
          fi
          if [ "$FILESERVER_CHANGED" != '' ]; then
            echo "::set-output name=fileserver::true"
          fi

  build-and-push:
    runs-on: ubuntu-latest
    needs: check-changed-files
    strategy:
      matrix:
        service: [frontend, backend, fileserver]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create Docker Buildx builder
        run: |
          docker buildx create --name mybuilder --use
          docker buildx inspect --bootstrap
          echo "Docker Buildx builder created"

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.service }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.service }}-

      - name: Build and push image for main
        if: github.ref == 'refs/heads/main' && needs.check-changed-files.outputs.${{ matrix.service }} == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./seonshine_${{ matrix.service }}
          file: ./seonshine_${{ matrix.service }}/Dockerfile.prod
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/seonshine_${{ matrix.service }}:prod
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build and push image for develop
        if: github.ref == 'refs/heads/develop' && needs.check-changed-files.outputs.${{ matrix.service }} == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./seonshine_${{ matrix.service }}
          file: ./seonshine_${{ matrix.service }}/Dockerfile.dev
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/seonshine_${{ matrix.service }}:dev
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: needs.check-changed-files.outputs.frontend == 'true' || needs.check-changed-files.outputs.backend == 'true' || needs.check-changed-files.outputs.fileserver == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > private_key
          chmod 600 private_key

      - name: SSH into server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "SSH connection successful"
            if [ ! -d /home/ubuntu/SEONSHINE ]; then
              mkdir -p /home/ubuntu/SEONSHINE
              git clone https://github.com/Seonjeongwan/SEONSHINE.git /home/ubuntu/SEONSHINE
            fi
            cd /home/ubuntu/SEONSHINE
            git reset --hard HEAD
            if [ "${{ github.ref }}" == 'refs/heads/main' ]; then
              git pull origin main
              export COMPOSE_HTTP_TIMEOUT=240
              docker-compose -f docker-compose.prod.yml down
              docker-compose -f docker-compose.prod.yml pull

              if [ "${{ needs.check-changed-files.outputs.frontend }}" == 'true' ]; then
                docker-compose -f docker-compose.prod.yml up -d frontend
              fi
              if [ "${{ needs.check-changed-files.outputs.backend }}" == 'true' ]; then
                docker-compose -f docker-compose.prod.yml up -d backend
              fi
              if [ "${{ needs.check-changed-files.outputs.fileserver }}" == 'true' ]; then
                docker-compose -f docker-compose.prod.yml up -d fileserver
              fi
            else
              git pull origin develop
              export COMPOSE_HTTP_TIMEOUT=240
              docker-compose -f docker-compose.dev.yml down
              docker-compose -f docker-compose.dev.yml pull

              if [ "${{ needs.check-changed-files.outputs.frontend }}" == 'true' ]; then
                docker-compose -f docker-compose.dev.yml up -d frontend
              fi
              if [ "${{ needs.check-changed-files.outputs.backend }}" == 'true' ]; then
                docker-compose -f docker-compose.dev.yml up -d backend
              fi
              if [ "${{ needs.check-changed-files.outputs.fileserver }}" == 'true' ]; then
                docker-compose -f docker-compose.dev.yml up -d fileserver
              fi
            fi
