name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./seonshine_frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/seonshine_frontend:latest

      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./seonshine_backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/seonshine_backend:latest

      - name: Build and push db image
        uses: docker/build-push-action@v2
        with:
          context: ./seonshine_db
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/seonshine_db:latest

      - name: Build and push fileserver image
        uses: docker/build-push-action@v2
        with:
          context: ./seonshine_fileserver
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/seonshine_fileserver:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: SSH into server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker-compose -f /path/to/docker-compose.yml pull
            docker-compose -f /path/to/docker-compose.yml up -d
