name: Build and Deploy

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "seonshine_frontend/**"
      - "seonshine_backend/**"
      - "seonshine_db/**"
      - "seonshine_fileserver/**"

jobs:
  check-changed-files:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.check.outputs.frontend }}
      backend: ${{ steps.check.outputs.backend }}
      fileserver: ${{ steps.check.outputs.fileserver }}
      any_changes: ${{ steps.check.outputs.any_changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check for changed files
        id: check
        run: |
          if [ "$(git rev-list --count HEAD)" -eq 1 ]; then
            echo "frontend=true" >> $GITHUB_ENV
            echo "backend=true" >> $GITHUB_ENV
            echo "fileserver=true" >> $GITHUB_ENV
            echo "any_changes=true" >> $GITHUB_ENV
            echo "frontend=true" >> $GITHUB_OUTPUT
            echo "backend=true" >> $GITHUB_OUTPUT
            echo "fileserver=true" >> $GITHUB_OUTPUT
            echo "any_changes=true" >> $GITHUB_OUTPUT
          else
            FRONTEND_CHANGED=$(git diff --name-only HEAD~1 HEAD | grep 'seonshine_frontend' | tr '\n' ' ' || echo '')
            BACKEND_CHANGED=$(git diff --name-only HEAD~1 HEAD | grep 'seonshine_backend' | tr '\n' ' ' || echo '')
            FILESERVER_CHANGED=$(git diff --name-only HEAD~1 HEAD | grep 'seonshine_fileserver' | tr '\n' ' ' || echo '')

            echo "FRONTEND_CHANGED=$FRONTEND_CHANGED" >> $GITHUB_ENV
            echo "BACKEND_CHANGED=$BACKEND_CHANGED" >> $GITHUB_ENV
            echo "FILESERVER_CHANGED=$FILESERVER_CHANGED" >> $GITHUB_ENV

            if [ "$FRONTEND_CHANGED" != '' ]; then
              echo "frontend=true" >> $GITHUB_ENV
              echo "frontend=true" >> $GITHUB_OUTPUT
            else
              echo "frontend=false" >> $GITHUB_ENV
              echo "frontend=false" >> $GITHUB_OUTPUT
            fi

            if [ "$BACKEND_CHANGED" != '' ]; then
              echo "backend=true" >> $GITHUB_ENV
              echo "backend=true" >> $GITHUB_OUTPUT
            else
              echo "backend=false" >> $GITHUB_ENV
              echo "backend=false" >> $GITHUB_OUTPUT
            fi

            if [ "$FILESERVER_CHANGED" != '' ]; then
              echo "fileserver=true" >> $GITHUB_ENV
              echo "fileserver=true" >> $GITHUB_OUTPUT
            else
              echo "fileserver=false" >> $GITHUB_ENV
              echo "fileserver=false" >> $GITHUB_OUTPUT
            fi

            if [ "$FRONTEND_CHANGED" != '' ] || [ "$BACKEND_CHANGED" != '' ] || [ "$FILESERVER_CHANGED" != '' ]; then
              echo "any_changes=true" >> $GITHUB_ENV
              echo "any_changes=true" >> $GITHUB_OUTPUT
            else
              echo "any_changes=false" >> $GITHUB_ENV
              echo "any_changes=false" >> $GITHUB_OUTPUT
            fi

            echo "Changed files:"
            echo "Frontend: $FRONTEND_CHANGED"
            echo "Backend: $BACKEND_CHANGED"
            echo "Fileserver: $FILESERVER_CHANGED"
            echo "any_changes: $any_changes"
          fi

  build-and-push-frontend:
    runs-on: ubuntu-latest
    needs: check-changed-files
    outputs:
      frontend_built: ${{ steps.set-output-frontend.outputs.built }}
    steps:
      - name: Set default output
        id: set-output-frontend
        run: echo "built=false" >> $GITHUB_OUTPUT

      - name: Checkout repository
        if: needs.check-changed-files.outputs.frontend == 'true'
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        if: needs.check-changed-files.outputs.frontend == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Create Docker Buildx builder
        if: needs.check-changed-files.outputs.frontend == 'true'
        run: |
          docker buildx create --name mybuilder --use
          docker buildx inspect --bootstrap
          echo "Docker Buildx builder created"

      - name: Log in to Docker Hub
        if: needs.check-changed-files.outputs.frontend == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Docker layers
        if: needs.check-changed-files.outputs.frontend == 'true'
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-frontend-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-frontend-

      - name: Build and push image for main
        id: build-frontend-main
        if: github.ref == 'refs/heads/main' && needs.check-changed-files.outputs.frontend == 'true'
        uses: docker/build-push-action@v3
        with:
          context: ./seonshine_frontend
          file: ./seonshine_frontend/Dockerfile.prod
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/seonshine_frontend:prod
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build and push image for develop
        id: build-frontend-develop
        if: github.ref == 'refs/heads/develop' && needs.check-changed-files.outputs.frontend == 'true'
        uses: docker/build-push-action@v3
        with:
          context: ./seonshine_frontend
          file: ./seonshine_frontend/Dockerfile.dev
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/seonshine_frontend:dev
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Set output
        if: needs.check-changed-files.outputs.frontend == 'true'
        run: echo "built=true" >> $GITHUB_OUTPUT

  build-and-push-backend:
    runs-on: ubuntu-latest
    needs: check-changed-files
    outputs:
      backend_built: ${{ steps.set-output-backend.outputs.built }}
    steps:
      - name: Set default output
        id: set-output-backend
        run: echo "built=false" >> $GITHUB_OUTPUT

      - name: Checkout repository
        if: needs.check-changed-files.outputs.backend == 'true'
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        if: needs.check-changed-files.outputs.backend == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Create Docker Buildx builder
        if: needs.check-changed-files.outputs.backend == 'true'
        run: |
          docker buildx create --name mybuilder --use
          docker buildx inspect --bootstrap
          echo "Docker Buildx builder created"

      - name: Log in to Docker Hub
        if: needs.check-changed-files.outputs.backend == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Docker layers
        if: needs.check-changed-files.outputs.backend == 'true'
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-backend-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-backend-

      - name: Build and push image for main
        id: build-backend-main
        if: github.ref == 'refs/heads/main' && needs.check-changed-files.outputs.backend == 'true'
        uses: docker/build-push-action@v3
        with:
          context: ./seonshine_backend
          file: ./seonshine_backend/Dockerfile.prod
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/seonshine_backend:prod
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build and push image for develop
        id: build-backend-develop
        if: github.ref == 'refs/heads/develop' && needs.check-changed-files.outputs.backend == 'true'
        uses: docker/build-push-action@v3
        with:
          context: ./seonshine_backend
          file: ./seonshine_backend/Dockerfile.dev
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/seonshine_backend:dev
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Set output
        if: needs.check-changed-files.outputs.backend == 'true'
        run: echo "built=true" >> $GITHUB_OUTPUT

  build-and-push-fileserver:
    runs-on: ubuntu-latest
    needs: check-changed-files
    outputs:
      fileserver_built: ${{ steps.set-output-fileserver.outputs.built }}
    steps:
      - name: Set default output
        id: set-output-fileserver
        run: echo "built=false" >> $GITHUB_OUTPUT

      - name: Checkout repository
        if: needs.check-changed-files.outputs.fileserver == 'true'
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        if: needs.check-changed-files.outputs.fileserver == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Create Docker Buildx builder
        if: needs.check-changed-files.outputs.fileserver == 'true'
        run: |
          docker buildx create --name mybuilder --use
          docker buildx inspect --bootstrap
          echo "Docker Buildx builder created"

      - name: Log in to Docker Hub
        if: needs.check-changed-files.outputs.fileserver == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Docker layers
        if: needs.check-changed-files.outputs.fileserver == 'true'
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-fileserver-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-fileserver-

      - name: Build and push image for main
        id: build-fileserver-main
        if: github.ref == 'refs/heads/main' && needs.check-changed-files.outputs.fileserver == 'true'
        uses: docker/build-push-action@v3
        with:
          context: ./seonshine_fileserver
          file: ./seonshine_fileserver/Dockerfile.prod
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/seonshine_fileserver:prod
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build and push image for develop
        id: build-fileserver-develop
        if: github.ref == 'refs/heads/develop' && needs.check-changed-files.outputs.fileserver == 'true'
        uses: docker/build-push-action@v3
        with:
          context: ./seonshine_fileserver
          file: ./seonshine_fileserver/Dockerfile.dev
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/seonshine_fileserver:dev
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Set output
        if: needs.check-changed-files.outputs.fileserver == 'true'
        run: echo "built=true" >> $GITHUB_OUTPUT

  deploy:
    needs:
      - check-changed-files
      - build-and-push-frontend
      - build-and-push-backend
      - build-and-push-fileserver
    runs-on: ubuntu-latest
    if: needs.check-changed-files.outputs.any_changes == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > private_key
          chmod 600 private_key

      - name: SSH into server for main
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "SSH connection successful"
            if [ ! -d /home/ubuntu/SEONSHINE ]; then
              mkdir -p /home/ubuntu/SEONSHINE
              git clone https://github.com/Seonjeongwan/SEONSHINE.git /home/ubuntu/SEONSHINE
            fi
            cd /home/ubuntu/SEONSHINE
            git reset --hard HEAD
            git pull origin main
            export COMPOSE_HTTP_TIMEOUT=600
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml pull

            services_to_restart=()
            if [ "${{ needs.check-changed-files.outputs.frontend }}" == 'true' ]; then
              services_to_restart+=('frontend')
            fi
            if [ "${{ needs.check-changed-files.outputs.backend }}" == 'true' ]; then
              services_to_restart+=('backend')
            fi
            if [ "${{ needs.check-changed-files.outputs.fileserver }}" == 'true' ]; then
              services_to_restart+=('fileserver')
            fi
            docker-compose -f docker-compose.prod.yml up -d "${services_to_restart[@]}"

      - name: SSH into server for develop
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "SSH connection successful"
            if [ ! -d /home/ubuntu/SEONSHINE ]; then
              mkdir -p /home/ubuntu/SEONSHINE
              git clone https://github.com/Seonjeongwan/SEONSHINE.git /home/ubuntu/SEONSHINE
            fi
            cd /home/ubuntu/SEONSHINE
            git reset --hard HEAD
            git pull origin develop
            export COMPOSE_HTTP_TIMEOUT=240
            docker-compose -f docker-compose.dev.yml down
            docker-compose -f docker-compose.dev.yml pull

            services_to_restart=()
            if [ "${{ needs.check-changed-files.outputs.frontend }}" == 'true' ]; then
              services_to_restart+=('frontend')
            fi
            if [ "${{ needs.check-changed-files.outputs.backend }}" == 'true' ]; then
              services_to_restart+=('backend')
            fi
            if [ "${{ needs.check-changed-files.outputs.fileserver }}" == 'true' ]; then
              services_to_restart+=('fileserver')
            fi
            docker-compose -f docker-compose.dev.yml up -d "${services_to_restart[@]}"
